### ISSUE TITLE
Additional CDP Links [Proposed]

### ISSUE THREAD

**Issue by klpatil** [dylanyoung-dev/dylanyoung-dev#1]
- **Interactive Sitecore CDP and Personalize Learning Mind Map** : https://sitecorebasics.wordpress.com/2021/12/22/interactive-sitecore-cdp-and-personalize-learning-mind-map/
- **5 Scenarios to demonstrate the power of Sitecore CDP/Personalize** : https://sitecorebasics.wordpress.com/2021/11/09/5-scenarios-to-demonstrate-the-power-of-sitecore-cdp-personalize/
- **Learnings from Sitecore CDP and Personalize Certification Exam** : https://sitecorebasics.wordpress.com/2021/12/22/learnings-from-sitecore-cdp-exam/
- **Send Abandoned Cart email using Sitecore CDP/Personalize** : https://sitecorebasics.wordpress.com/2021/11/25/send-abandoned-cart-email-using-sitecore-cdp-personalize/
- **Customer’s orders tab not showing order while using Sitecore CDP** : https://sitecorebasics.wordpress.com/2021/11/25/customers-orders-tab-not-showing-order-while-using-sitecore-cdp/
- **Sitecore CDP Troubleshooting Guide** : https://sitecorebasics.wordpress.com/2021/11/25/sitecore-cdp-troubleshooting-guide/

**Comment by dylanyoung-dev** [comment]
I've pulled in your links and those on Twitter into the document.  I may eventually move this list to it's own repo or somewhere else.  But I appreciate any others that wish to contribute, since it helps everyone in the long run!
